const BAD_REQUEST = 400;
const INTERNAL_SERVERE_ERROR = 500;
const NOT_FOUND = 404;
const CONFLICTING_REQUEST = 409;
const UNAUTHORIZED = 401;
const FORDBIDDEN = 403;

module.exports = {
  BAD_REQUEST, INTERNAL_SERVERE_ERROR, NOT_FOUND, CONFLICTING_REQUEST, UNAUTHORIZED, FORDBIDDEN,
};
